terrestris/mapfish-print-manager

dist/manager/BaseMapFishPrintManager.js
dist/manager/MapFishPrintV2Manager.js
src/manager/BaseMapFishPrintManager.js
src/manager/MapFishPrintV2Manager.js

This introduces the `legendFilter` function to the base and V2 manager.

Introduces legendFilter function

---

package.json

chore(package): update webpack-cli to version 3.0.6

---

package.json

chore(package): update webpack to version 4.15.0

---

dist/serializer/VectorSerializer.js
src/serializer/VectorSerializer.js

I think the title says it all
@dnlkoch please review

Optimized imports of lodash, saves ~400KB in production builds

---

package.json

chore(package): update webpack to version 4.18.1

---

package.json

chore(package): update babel-plugin-import to version 1.9.1

---

package.json

chore(package): update webpack-dev-server to version 3.1.14

---

package.json

fix(package): update parse-css-font to version 4.0.0

---

package.json

chore(package): update webpack to version 4.29.5

---

package.json

chore(package): update webpack-dev-server to version 3.3.1

---

src/manager/MapFishPrintV3Manager.js

* make poll timeout configurable
* ensure that print download url will be set correctly by using of absolute path
Credits go to @hwbllmnn 
Please review.

Minor fixes for PrintManager v3

---

package.json

chore(package): update webpack-dev-server to version 3.4.1

---

package.json

See in title.
Follow up of #159.

Build docs on before release/publish

---

package.json

chore(package): update webpack to version 4.32.2

---

package.json

chore(package): update webpack-dev-server to version 3.5.1

---

spec/util/Shared.spec.js
src/util/Shared.js

Enhance getMapLayers for group layers (nested)

---

package.json

chore(package): update webpack-cli to version 3.3.5

---

package.json

chore(package): update webpack to version 4.40.2

---

package.json

chore(package): update webpack-dev-server to version 3.10.1

---

package.json

chore(package): update webpack to version 4.41.5

---

README.md

Highlight JS code block in README

---

package.json

Don't push to GitHub manually as np pushes the changes already.

Update release script

---

spec/util/Shared.spec.js
src/util/Shared.js

Add question mark to query string if needed only

---

package-lock.json
package.json
spec/util/Shared.spec.js
src/util/Shared.js

Filter layers contained in invisible layer groups

---

src/manager/MapFishPrintV3Manager.js

More or less follow up of #318. Adds sanitizing URL check for download URL as well.
@terrestris/devs

Sanitize download url as well

---

src/serializer/MapFishPrintV3WMTSSerializer.js

Actually pass modified url to serialized layer

---

src/serializer/MapFishPrintV3StamenSerializer.js

Adds a serializer for V3 to serialize Stamen layers (toner, terrain, watercolor, labels,...)

added serializer for Stamen layers for MapFish V3

---

src/serializer/MapFishPrintV3GeoJsonSerializer.js

removed a typo that was preventing a successful test

fixed typo that is preventing a successfull test

---

src/serializer/MapFishPrintV3WMTSSerializer.js

This removes the limitation of the matrix entries.

Add all given matrix entries to the set

---

dist/serializer/VectorSerializer.js
package.json
src/serializer/VectorSerializer.js

Fixes the rotation of triangles.
@terrestris/devs Please review.

Fix triangle rotation

---

.github/workflows/on-pull-request.yml
.gitignore
.npmrc
.travis.yml
package-lock.json
package.json
src/serializer/MapFishPrintV2VectorSerializer.js

Mirror of https://github.com/terrestris/mapfish-print-manager/pull/376 for ol5 branch.

introduce github workflow on pull request

---

package.json
tsconfig.json

Fixes the build to actually output files.
@terrestris/devs Please review.

fix: fix build

---

src/manager/BaseMapFishPrintManager.ts
src/manager/MapFishPrintV2Manager.ts
src/manager/MapFishPrintV3Manager.ts
src/observable/Observable.ts

This makes several members and methods intended for private usage protected.

Limit exposed API functions/members

---

.gitignore
jest.config.js
jest.setup.js
package-lock.json
package.json
src/manager/BaseMapFishPrintManager.ts
src/manager/MapFishPrintV3Manager.ts

Feature: Add setter for legend filter and update OpenLayers to v7.2.2

---

src/interaction/InteractionTransform.js

This PR fixes the event handler function names to match OL5 API.
Thanks @annarieger 

Fixes event handler function names  (ol5)

---

spec/manager/MapFishPrintV3Manager.spec.ts
src/manager/MapFishPrintV3Manager.ts

fix: getters and setters of customMapParams

---

src/manager/BaseMapFishPrintManager.ts

Follow-up fix after feature to set locale print app.  @dnlkoch

fix: print extent interaction

---

src/manager/BaseMapFishPrintManager.ts
tasks/update-gh-pages.js

See title.
@terrestris/devs Please review

Add getter for `extentLayer`

---

package-lock.json
package.json

fix: adds missing build script and remove np dependency

---

.github/workflows/on-push-main.yml

fix: remove duplicate docs build

---

.github/workflows/on-push-main.yml

fix: disable husky for npx release

---

.github/workflows/on-push-main.yml
.releaserc
jest.config.js
package-lock.json
package.json
src/serializer/MapFishPrintV2VectorSerializer.ts
src/serializer/MapFishPrintV3GeoJsonSerializer.ts
src/serializer/MapFishPrintV3StamenSerializer.ts

See title.
Introduced for maintanance purpose.

feat: introduce Openlayers 8 maintenance branch

---

.github/workflows/on-pull-request.yml
spec/serializer/MapFishPrintV3GeoJsonSerializer.spec.js

fix: tests and introduce pipeline for v5-main branch

---

jest.config.cjs
package-lock.json
package.json
src/interaction/InteractionTransform.ts
src/manager/BaseMapFishPrintManager.ts
src/serializer/MapFishPrintV2VectorSerializer.ts
src/serializer/MapFishPrintV3GeoJsonSerializer.ts

This updates to the latest `ol`.
Since the peer dependency is also updated, this is considered as **breaking change**.

Update to latest `ol`
