terrestris/mapfish-print-manager

- dist/serializer/VectorSerializer.js
- src/serializer/VectorSerializer.js
This MR fixes print of vector features which are based on `ol.geom.Circle` geometry type.
As GeoJSON format cannot work with circle geometries we need to transform these to `ol.geom.Polygon` to be able to print it.
Please review @dnlkoch @KaiVolland
> Fix print of vector features with circle geometry

- src/serializer/VectorSerializer.js
This PR adds a check for `styles` to `VectorSerializer` if `styleFunction` returns a single instance of `OlStyleStyle`.
As the serializer assumes that styles is an array of `OlStyleStyle` it is simply creates one here.
> VectorSerializer: switch to style array

- dist/manager/BaseMapFishPrintManager.js
- src/manager/BaseMapFishPrintManager.js
This fix enables to overwrite default options defined for `OlInteractionTransform` by passing of `transformOpts` object during manager initialization.
```javascript
const manager = new MapFishPrintV2Manager({
url: 'http://url.com',
map: map,
... 
transformOpts: {
rotate: false,
scale: false
...
}
});
```
~~Additionally some dependencies were bumped to newer versions.~~ -> see #8
Please review @dnlkoch
> Fix `transformOpts` assignment for `OlInteractionTransform`

- package.json
- webpack.common.config.js
Since `greenkeeper` was enabled for the project it has updated a webpack dependency to version 4.x (#9). So we have to adapt some configs to match changed API now.
Please review @dnlkoch
> Update to `webpack` version 4

- src/interaction/InteractionTransform.js
Handler names for `up`, `down`, `drag` and `move` events within [`ol/interaction/Pointer`](https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Pointer.js) don't end with underscore in `ol5` as they did in `ol4` any more.
E.g. compare [`ol4`](https://github.com/openlayers/openlayers/blob/v4.6.5/src/ol/interaction/pointer.js#L41)  vs. [`ol5`](https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Pointer.js#L57).
This MR removes underscores and thus restores transform interaction functionality while operating with ol5.
Please review @dnlkoch
> Adapt event handler function names to match OL5 API

- src/manager/BaseMapFishPrintManager.js
- src/manager/MapFishPrintV3Manager.js
Title says it all.
In addition, timeout property was moved to `BaseMapFishPrintManager`
> Reverse layer ordering for MapFish print v3

- src/manager/BaseMapFishPrintManager.js
- src/manager/MapFishPrintV3Manager.js
Allow user to provide some custom map parameters which can be interpreted by mapfish v3 while printing.
The whole list of parameters is defined under http://mapfish.github.io/mapfish-print-doc/attributes.html#!map (section "Inputs").
Additionally fix setting of user defined print scales for manager v3 (previously fallback value could never be used since `customPrintScales` will be instantiated as empty array initially and always defined).
Please review @dnlkoch
> Add support for customizable map parameters for mapfish v3

- README.md
- package.json
- spec/serializer/MapFishPrintV2VectorSerializer.spec.js
- src/manager/BaseMapFishPrintManager.js
- src/serializer/MapFishPrintV2VectorSerializer.js
- src/serializer/MapFishPrintV3GeoJsonSerializer.js
Upgrade to `ol` version 6.x considering [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0) for release 6.0.0.
> Upgrade to OpenLayers v6

- package.json
- spec/manager/MapFishPrintV3Manager.spec.js
- src/manager/MapFishPrintV3Manager.js
Currently, the determination of `basePath`  / `baseHost` doesn't work properly for relative URLs that reference an endpoint more than two levels above to the application that uses  `mapfish-print-manager`. 
This PR introduces usage of `query-string` and `url-parse` for its proper detection.
:exclamation: This tackles V5 of  `mapfish-print-manager` using OpenLayers 5. Therefore, a new branch `ol5` was created as base for merge.
Pltz review @terrestris/devs
> Use query-string and url-parse for basepath detection - V5.x.x

- package-lock.json
- package.json
- spec/manager/MapFishPrintV3Manager.spec.js
- src/manager/MapFishPrintV3Manager.js
Currently, the determination of `basePath`  / `baseHost` doesn't work properly for relative URLs that reference an endpoint more than two levels above to the application that uses  `mapfish-print-manager`. 
This PR introduces usage of `query-string` and `url-parse` for its proper detection.
Pltz review @terrestris/devs
> Use query-string and url-parse for basepath detection

- src/manager/MapFishPrintV3Manager.js
`URL.host` already contains both hostname and port if present. Currently the port was included twice because of this (e.g. `https://localhost:9090:9090/print/`)
This just restores the version initially proposed in https://github.com/terrestris/mapfish-print-manager/pull/295
@devs Please review
> remove duplicated port from base url detection

- src/manager/BaseMapFishPrintManager.js
Increase the default timeout for polling the print result to 30 seconds.
> Increase default timeout to 30 seconds

- src/util/Shared.js
Check if layer has property `legendGraphic` which contains the URL to a customized legend graphic and, if set, return it instead of `GetLegendGraphic` request URL.
> Enable custom static legend graphic sources

- src/manager/BaseMapFishPrintManager.js
- src/manager/MapFishPrintV2Manager.js
- src/util/Shared.js
More or less follow up of https://github.com/terrestris/mapfish-print-manager/pull/313
Enables legend image print for WMTS layers.
> Enable printing of legends for WMTS layers

- spec/util/Shared.spec.js
- src/manager/MapFishPrintV3Manager.js
- src/util/Shared.js
Avoid dublicated slashes in URL strings which can possibly lead to request aborting
e.g. `https://localhost:9090/print/default//status/status-hash.json` should become `https://localhost:9090/print/default/status/status-hash.json`
@terrestris/devs
> Fix double slashes in urls

- src/serializer/BaseSerializer.js
- src/serializer/MapFishPrintV2VectorSerializer.js
- src/serializer/MapFishPrintV2WMSSerializer.js
- src/serializer/MapFishPrintV3GeoJsonSerializer.js
- src/serializer/MapFishPrintV3OSMSerializer.js
- src/serializer/MapFishPrintV3WMSSerializer.js
- src/serializer/MapFishPrintV3WMTSSerializer.js
This suggests to remove the unsupported layer attributes min- and maxScaleDenominator. As the base serialize method is thereby not needed anymore, it has been removed as well.
> Remove unsupported layer attributes

- src/serializer/MapFishPrintV3WMTSSerializer.js
This fixes serialization of WMTS layers by:
* Setting the style path variable according the mapfish print spec (lowercase).
* Reading out the tile grid origin for the given resolution, if any.
> Fix serializing WMTS layers

- src/util/Shared.js
This suggests to remove the OlSourceWMTS from condition as WMTS isn't generally providing a `GetLegendGraphic` endpoint and the code is not compatible with the given source, e.g. `getParams()` is not available for it.
> Fix legend request generation for WMTS layers

- src/serializer/MapFishPrintV3GeoJsonSerializer.js
This fixes the serialization of the GeoJSON styles by:
* Readding the styles to the print payload.
* Hiding the geometries from the text style.
> Fix style serialization

- dist/interaction/InteractionTransform.js
- dist/manager/BaseMapFishPrintManager.js
- dist/manager/MapFishPrintV2Manager.js
- dist/serializer/VectorSerializer.js
- dist/serializer/WMSSerializer.js
- dist/util/Shared.js
- src/serializer/VectorSerializer.js
This MR updates the `VectorSerializer` from version` 2.0.0` to get the `graphicName` of a `RegularShape` (triangle, square, cross, x and star). 
Should be released afterwards as version 2.0.0-1, since version 2.0.1 already requires a newer OL version.
> Determine the graphicName of a RegularShape

- src/serializer/MapFishPrintV2VectorSerializer.js
This MR fixes a typo (`String` => `string`) in a JSDoc comment. 
@terrestris/devs please note, will merge soon.
> Fixes a typo in JSDoc comment

- dist/manager/BaseMapFishPrintManager.js
- src/manager/BaseMapFishPrintManager.js
Similar to https://github.com/terrestris/mapfish-print-manager/commit/d2719a209d6cc63b9c7f2ad19e9717e10e1a1121, add `customPrintScales` parameter to v2 branch, enabling to pass user defined array of print scales used by manager.
If passed, the default scale array from capabilities will be ignored.
Also updates dist sources for `BaseMapFishPrintManager` which seems to be outdated (and commited on the old v2 branch).
> Enable passig of custom print scales (v2)

- jest.config.js
- package.json
- src/interaction/InteractionTransform.js
- src/manager/MapFishPrintV2Manager.js
- src/serializer/MapFishPrintV2VectorSerializer.js
At the moment there are two branches [`ol5`](https://github.com/terrestris/mapfish-print-manager/tree/ol5) and [`v2.0.0-master`](https://github.com/terrestris/mapfish-print-manager/tree/v2.0.0-master) which are both based on OpenLayers v5.
This PR proposes to put changes from both branches together and merge them into `ol5` branch, which should be used in older ol5 based projects and maintained furthermore. After merge, the branch `v2.0.0-master` will be deleted.
It will be also proposed to publish a ol5 releases versions tagged as `x.x.x-ol5` (e.g. starting with `1.0.0-ol5`). For cleanliness and better traceability it could be useful to unpublish the already existing relases tagged with `v2.0.0-x` or at least mark them as deprecated or similar.
> Merge OpenLayers v5 branches together

- package.json
- spec/serializer/MapFishPrintV3GeoJsonSerializer.spec.js
- src/index.js
- src/manager/MapFishPrintV3Manager.js
- src/serializer/MapFishPrintV3GeoJsonSerializer.js
- Adds missing `BaseMapFishPrintManager` export
- Fixes `getBasePath`
> Fix for OL5 branch

- src/manager/BaseMapFishPrintManager.js
- src/manager/MapFishPrintV2Manager.js
- src/manager/MapFishPrintV3Manager.js
This PR adds a new Property to `BaseMapFishPrintManager`, called `customDpis`.
It is intended for a user to use DPI values other than the ones in the capabilities or given as fallback in case the capabilities values do not exist.
`MapFishPrintV2Manager` and `MapFishPrintV3Manager` have also been slightly changed in order to consider this new property.
> New customDPIs property

- src/manager/BaseMapFishPrintManager.ts
This takes the device pixel ratio into account when retrieving the pixels of the extent-geometry in order to draw the shadow mask on the canvas.
Before this change, when using a device with device pixel ratio != 1 like e.g. iPad, the mask would have a big offset and is not in sync with the extent-geometry .
Related discussion: https://github.com/openlayers/openlayers/issues/2904
To see the issue in action just watch the extent-geometry and the "shadow-mask" in a apple device emulator of your browser and pan the map.
> fix: respect device pixel ratio when retrieving pixels from map

- src/manager/BaseMapFishPrintManager.ts
This PR sets the legendUrl to `undefined` when the string is empty. This is necessary because mapfish print couldn't find a legend under the previously submitted string.
> Provide correct legendUrl value if none is set fro WMTS

- spec/serializer/MapFishPrintV3WMTSSerializer.spec.ts
- src/serializer/MapFishPrintV3WMTSSerializer.ts
See title.
Serialized WMTS layers having dimension configuration (e.g. time) sould have the following structure in request payload:
```
…
dimensionParams: {
Time: 'current'
},
dimensions: ['Time'],
…
```
For this (and the `MapFishPrintV3WMTSSerializer`) an test has been added as well.
> fix: dimension serialization for WMTS layers for Mapfish v3

- .releaserc
This PR fixes an error that occurred during `ol-8` release workflow (see also https://github.com/terrestris/mapfish-print-manager/actions/runs/8534353909/job/23378590177)
> Fix .releaserc channel for ol-8 releases

- package-lock.json
- package.json
With this PR ol is used in v9.1.0 and a mistake in the versioning is fixed as the use of ol9 should generate a new version 12 of mapfish-print-manager. In addition, some dependency updates will be integrated into the new version.
> Uses ol v9.1.0 and adjusts a version mismatch
